version: '3'
services:
  nobot-redis:
    image: redis
    ports:
      - '6379:6379'
    restart: always
  nobot-database:
    image: postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: nobot
      POSTGRES_USER: nobot
      POSTGRES_PASSWORD: nobot
    volumes:
      - nobot-pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - '5433:5432'
    restart: always
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '8000:80'
    restart: always
  kong:
    build:
      context: ./packages/tools/kong
      dockerfile:  Dockerfile.dev
    ports:
      - '4000:8000'
      - '4433:8433'
      - '127.0.0.1:4001:8001'
      - '127.0.0.1:4444:8444'
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/config.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
  auction-sniping:
    build:
      context: ./
      dockerfile: ./packages/api/auction-sniping/Dockerfile.dev
    volumes:
      - ./config:/usr/src/app/config
      - ./packages/core/commons:/usr/src/app/packages/core/commons
      - ./packages/core/database:/usr/src/app/packages/core/database
      - ./packages/api/auction-sniping:/usr/src/app/packages/api/auction-sniping
      - /usr/src/app/packages/core/commons/node_modules
      - /usr/src/app/packages/core/database/node_modules
      - /usr/src/app/packages/api/auction-sniping/node_modules
    ports:
      - '4001:3000'
    environment:
      CONFIG_PROFILE: ${CONFIG_PROFILE}
  card:
    build:
      context: ./
      dockerfile: ./packages/api/card/Dockerfile.dev
    volumes:
      - ./config:/usr/src/app/config
      - ./packages/core/commons:/usr/src/app/packages/core/commons
      - ./packages/core/database:/usr/src/app/packages/core/database
      - ./packages/api/card:/usr/src/app/packages/api/card
      - /usr/src/app/packages/core/commons/node_modules
      - /usr/src/app/packages/core/database/node_modules
      - /usr/src/app/packages/api/card/node_modules
    ports:
      - '4002:3000'
    environment:
      CONFIG_PROFILE: ${CONFIG_PROFILE}
  account:
    build:
      context: ./
      dockerfile: ./packages/api/account/Dockerfile.dev
    volumes:
      - ./config:/usr/src/app/config
      - ./packages/core/commons:/usr/src/app/packages/core/commons
      - ./packages/core/database:/usr/src/app/packages/core/database
      - ./packages/api/account:/usr/src/app/packages/api/account
      - /usr/src/app/packages/core/commons/node_modules
      - /usr/src/app/packages/core/database/node_modules
      - /usr/src/app/packages/api/account/node_modules
    ports:
      - '4003:3000'
    environment:
      CONFIG_PROFILE: ${CONFIG_PROFILE}
  auction:
    build:
      context: ./
      dockerfile: ./packages/api/auction/Dockerfile.dev
    volumes:
      - ./config:/usr/src/app/config
      - ./packages/core/commons:/usr/src/app/packages/core/commons
      - ./packages/core/database:/usr/src/app/packages/core/database
      - ./packages/api/auction:/usr/src/app/packages/api/auction
      - /usr/src/app/packages/core/commons/node_modules
      - /usr/src/app/packages/core/database/node_modules
      - /usr/src/app/packages/api/auction/node_modules
    ports:
      - '4004:3000'
    environment:
      CONFIG_PROFILE: ${CONFIG_PROFILE}
      HOUR_OFFSET: ${HOUR_OFFSET}
  story:
    build:
      context: ./
      dockerfile: ./packages/api/story/Dockerfile.dev
    volumes:
      - ./config:/usr/src/app/config
      - ./packages/core/commons:/usr/src/app/packages/core/commons
      - ./packages/core/database:/usr/src/app/packages/core/database
      - ./packages/api/story:/usr/src/app/packages/api/story
      - /usr/src/app/packages/core/commons/node_modules
      - /usr/src/app/packages/core/database/node_modules
      - /usr/src/app/packages/api/story/node_modules
    ports:
      - '4005:3000'
    environment:
      CONFIG_PROFILE: ${CONFIG_PROFILE}
  tutorial:
    build:
      context: ./
      dockerfile: ./packages/api/tutorial/Dockerfile.dev
    volumes:
      - ./config:/usr/src/app/config
      - ./packages/core/commons:/usr/src/app/packages/core/commons
      - ./packages/core/database:/usr/src/app/packages/core/database
      - ./packages/api/tutorial:/usr/src/app/packages/api/tutorial
      - /usr/src/app/packages/core/commons/node_modules
      - /usr/src/app/packages/core/database/node_modules
      - /usr/src/app/packages/api/tutorial/node_modules
    ports:
      - '4006:3000'
    environment:
      CONFIG_PROFILE: ${CONFIG_PROFILE}
  action:
    build:
      context: ./
      dockerfile: ./packages/api/action/Dockerfile.dev
    volumes:
      - ./config:/usr/src/app/config
      - ./packages/core/commons:/usr/src/app/packages/core/commons
      - ./packages/core/database:/usr/src/app/packages/core/database
      - ./packages/api/action:/usr/src/app/packages/api/action
      - /usr/src/app/packages/core/commons/node_modules
      - /usr/src/app/packages/core/database/node_modules
      - /usr/src/app/packages/api/action/node_modules
    ports:
      - '4007:3000'
    environment:
      CONFIG_PROFILE: ${CONFIG_PROFILE}
  battle:
    build:
      context: ./
      dockerfile: ./packages/api/battle/Dockerfile.dev
    volumes:
      - ./config:/usr/src/app/config
      - ./packages/core/commons:/usr/src/app/packages/core/commons
      - ./packages/core/database:/usr/src/app/packages/core/database
      - ./packages/api/battle:/usr/src/app/packages/api/battle
      - /usr/src/app/packages/core/commons/node_modules
      - /usr/src/app/packages/core/database/node_modules
      - /usr/src/app/packages/api/battle/node_modules
    ports:
      - '4008:3000'
    environment:
      CONFIG_PROFILE: ${CONFIG_PROFILE}
  event:
    build:
      context: ./
      dockerfile: ./packages/api/event/Dockerfile.dev
    volumes:
      - ./config:/usr/src/app/config
      - ./packages/core/commons:/usr/src/app/packages/core/commons
      - ./packages/core/database:/usr/src/app/packages/core/database
      - ./packages/api/event:/usr/src/app/packages/api/event
      - /usr/src/app/packages/core/commons/node_modules
      - /usr/src/app/packages/core/database/node_modules
      - /usr/src/app/packages/api/event/node_modules
    ports:
      - '4009:3000'
    environment:
      CONFIG_PROFILE: ${CONFIG_PROFILE}
volumes:
    nobot-pgdata:
