version: '3'
services:
  nobot-redis:
    image: redis
    ports:
      - '6379:6379'
  nobot-database:
    image: postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: nobot
      POSTGRES_USER: nobot
      POSTGRES_PASSWORD: nobot
    volumes:
      - nobot-pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - '5433:5432'
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '8000:80'
    restart: always
  auction-sniping:
    build:
      context: ./
      dockerfile: ./packages/api/auction-sniping/Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/packages/core/database/node_modules
      - /usr/src/app/packages/core/commons/node_modules
      - /usr/src/app/packages/api/auction-sniping/node_modules
      - /usr/src/app/packages/api/account-manager
      - /usr/src/app/packages/api/auction
      - /usr/src/app/packages/api/card
      - /usr/src/app/packages/api/sample
      - /usr/src/app/packages/tools
      - .:/usr/src/app
    ports:
      - '4001:3000'
    environment:
      CONFIG_PROFILE: ${CONFIG_PROFILE}
  card:
    build:
      context: ./
      dockerfile: ./packages/api/card/Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/packages/core/database/node_modules
      - /usr/src/app/packages/core/commons/node_modules
      - /usr/src/app/packages/api/card/node_modules
      - /usr/src/app/packages/api/auction
      - /usr/src/app/packages/api/auction-sniping
      - /usr/src/app/packages/api/account-manager
      - /usr/src/app/packages/api/sample
      - /usr/src/app/packages/tools
      - .:/usr/src/app
    ports:
      - '4002:3000'
    environment:
      CONFIG_PROFILE: ${CONFIG_PROFILE}
  account-manager:
    build:
      context: ./
      dockerfile: ./packages/api/account-manager/Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/packages/core/database/node_modules
      - /usr/src/app/packages/core/commons/node_modules
      - /usr/src/app/packages/api/account-manager/node_modules
      - /usr/src/app/packages/api/auction
      - /usr/src/app/packages/api/auction-sniping
      - /usr/src/app/packages/api/card
      - /usr/src/app/packages/api/sample
      - /usr/src/app/packages/tools
      - .:/usr/src/app
    ports:
      - '4003:3000'
    environment:
      CONFIG_PROFILE: ${CONFIG_PROFILE}
  auction:
    build:
      context: ./
      dockerfile: ./packages/api/auction/Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/packages/core/database/node_modules
      - /usr/src/app/packages/core/commons/node_modules
      - /usr/src/app/packages/api/auction/node_modules
      - /usr/src/app/packages/api/account-manager
      - /usr/src/app/packages/api/auction-sniping
      - /usr/src/app/packages/api/card
      - /usr/src/app/packages/api/sample
      - /usr/src/app/packages/tools
      - .:/usr/src/app
    ports:
      - '4004:3000'
    environment:
      CONFIG_PROFILE: ${CONFIG_PROFILE}
volumes:
    nobot-pgdata:
