version: '3'
services:
  nobot-redis:
    image: redis
  nobot-database:
    image: postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: nobot
      POSTGRES_USER: nobot
      POSTGRES_PASSWORD: nobot
    volumes:
      - nobot-pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
  nobot-token-manager:
    build:
      context: ./
      dockerfile: ./packages/token-manager/Dockerfile
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/packages/token-manager/node_modules
      - .:/usr/src/app
volumes:
    nobot-pgdata:
