version: '3'
services:
  nobot-redis:
    image: redis
    ports:
      - '6379:6379'
  nobot-database:
    image: postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: nobot
      POSTGRES_USER: nobot
      POSTGRES_PASSWORD: nobot

    volumes:
      - nobot-pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - '5433:5432'
  auction-sniping:
    build:
      context: ./
      dockerfile: ./packages/api/auction-sniping/Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/packages/core/database/node_modules
      - /usr/src/app/packages/core/commons/node_modules
      - /usr/src/app/packages/api/auction-sniping/node_modules
      - .:/usr/src/app
    ports:
      - '4001:3000'
  card:
    build:
      context: ./
      dockerfile: ./packages/api/card/Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/packages/core/database/node_modules
      - /usr/src/app/packages/core/commons/node_modules
      - /usr/src/app/packages/api/card/node_modules
      - .:/usr/src/app
    ports:
      - '4002:3000'
  account-manager:
    build:
      context: ./
      dockerfile: ./packages/api/account-manager/Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/packages/core/database/node_modules
      - /usr/src/app/packages/core/commons/node_modules
      - /usr/src/app/packages/api/account-manager/node_modules
      - .:/usr/src/app
    ports:
      - '4003:3000'
volumes:
    nobot-pgdata:
