---
projectName: api_auction_sniping
<<: !config config

---
projectName: api_account
<<: !config config

---
projectName: api_card
<<: !config config

---
projectName: api_auction
<<: !config config

---
projectName: api_sample
<<: !config config

---
projectName: api_story
<<: !config config

---
projectName: api_tutorial
<<: !config config

---
projectName: api_action
<<: !config config

---
projectName: api_battle
<<: !config config

---
  projectName: api_event
  <<: !config config
