---
projectName: api_auction_sniping
<<: !config config

---
projectName: api_account_manager
<<: !config config

---
projectName: api_card
<<: !config config

---
  projectName: api_auction
  <<: !config config

---
  projectName: api_sample
  <<: !config config

---
  projectName: api_story
  <<: !config config

---
  projectName: api_tutorial
  <<: !config config
